apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: app
          image: vcr.vngcloud.vn/60108-cuongdm3/rails-hello-world
          ports:
            - name: web
              containerPort: 3000
              protocol: TCP
---

kind: Service
apiVersion: v1
metadata:
  name: hello-world
  annotations:
    vks.vngcloud.vn/monitor-http-path: "/"
    vks.vngcloud.vn/monitor-http-method: "get"
    vks.vngcloud.vn/monitor-protocol: "http"
spec:
  type: LoadBalancer
  selector:
    app: hello-world
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: web